// lib/data.ts
import { Product } from './types';

export const products: Product[] = [
  // PRODUTOS INICIAIS (4)
  {
    id: '171672',
    Selecionar: false,
    Código: '171672',
    Descrição: 'ANADOR 500MG 10CPR (3BL X 4CPR)',
    Fabricante: 'Opella',
    Preço: 136.25,
    Desconto: '2.00%',
    'Preço c/ Desconto': 133.53,
    EmEstoque: true,
  },
  {
    id: '171298',
    Selecionar: false,
    Código: '171298',
    Descrição: 'ANADOR 500MG 24CPR (6BL X 4CPR)',
    Fabricante: 'Opella',
    Preço: 298.52,
    Desconto: '2.00%',
    'Preço c/ Desconto': 292.41,
    EmEstoque: false,
  },
  {
    id: '10375',
    Selecionar: false,
    Código: '10375',
    Descrição: 'ANADOR 500MG 4CPR',
    Fabricante: 'Opella',
    Preço: 21.96,
    Desconto: '2.00%',
    'Preço c/ Desconto': 21.52,
    EmEstoque: true,
  },
  {
    id: '10383',
    Selecionar: false,
    Código: '10383',
    Descrição: 'ANADOR 500MG 512CPR (128 X 4CPR)',
    Fabricante: 'Opella',
    Preço: 544.60,
    Desconto: '2.00%',
    'Preço c/ Desconto': 533.71,
    EmEstoque: false,
  },

  // NOVOS 100 PRODUTOS GERADOS
  {
    id: '200001',
    Selecionar: false,
    Código: 'MED001',
    Descrição: 'LOSARTANA 50MG 30CPR (Genérico)',
    Fabricante: 'Eurofarma',
    Preço: 35.80,
    Desconto: '15.00%',
    'Preço c/ Desconto': 30.43,
    EmEstoque: true,
  },
  {
    id: '200002',
    Selecionar: false,
    Código: 'MED002',
    Descrição: 'DIPIRONA SÓDICA 500MG 20CPR',
    Fabricante: 'Neo Química',
    Preço: 12.50,
    Desconto: '5.00%',
    'Preço c/ Desconto': 11.88,
    EmEstoque: true,
  },
  {
    id: '200003',
    Selecionar: false,
    Código: 'MED003',
    Descrição: 'NIMESULIDA 100MG 12CPR (Anti-inflamatório)',
    Fabricante: 'EMS Pharma',
    Preço: 28.90,
    Desconto: '10.00%',
    'Preço c/ Desconto': 26.01,
    EmEstoque: true,
  },
  {
    id: '200004',
    Selecionar: false,
    Código: 'MED004',
    Descrição: 'SIMETICONA 75MG/ML GOTAS 15ML',
    Fabricante: 'Cimed',
    Preço: 18.75,
    Desconto: '0.00%',
    'Preço c/ Desconto': 18.75,
    EmEstoque: true,
  },
  {
    id: '200005',
    Selecionar: false,
    Código: 'MED005',
    Descrição: 'TORSILAX 30CPR (Analgésico e Relaxante)',
    Fabricante: 'Hypera Pharma',
    Preço: 45.00,
    Desconto: '8.00%',
    'Preço c/ Desconto': 41.40,
    EmEstoque: true,
  },
  {
    id: '200006',
    Selecionar: false,
    Código: 'MED006',
    Descrição: 'CIMEGRIPE 20CPR (Gripes e Resfriados)',
    Fabricante: 'Cimed',
    Preço: 22.30,
    Desconto: '0.00%',
    'Preço c/ Desconto': 22.30,
    EmEstoque: false,
  },
  {
    id: '200007',
    Selecionar: false,
    Código: 'MED007',
    Descrição: 'PURAN T4 100MCG 30CPR (Tireoide)',
    Fabricante: 'Sanofi',
    Preço: 68.90,
    Desconto: '3.00%',
    'Preço c/ Desconto': 66.83,
    EmEstoque: true,
  },
  {
    id: '200008',
    Selecionar: false,
    Código: 'MED008',
    Descrição: 'NEOSORO SOLUÇÃO NASAL 30ML',
    Fabricante: 'Neo Química',
    Preço: 15.60,
    Desconto: '0.00%',
    'Preço c/ Desconto': 15.60,
    EmEstoque: true,
  },
  {
    id: '200009',
    Selecionar: false,
    Código: 'MED009',
    Descrição: 'DORFLEX 36CPR (Analgésico e Relaxante)',
    Fabricante: 'Sanofi',
    Preço: 39.99,
    Desconto: '7.00%',
    'Preço c/ Desconto': 37.19,
    EmEstoque: true,
  },
  {
    id: '200010',
    Selecionar: false,
    Código: 'MODA01',
    Descrição: 'Camiseta Dry-Fit Masculina P',
    Fabricante: 'Fitness Wear',
    Preço: 79.90,
    Desconto: '10.00%',
    'Preço c/ Desconto': 71.91,
    EmEstoque: true,
  },
  {
    id: '200011',
    Selecionar: false,
    Código: 'MODA02',
    Descrição: 'Calça Legging Feminina G',
    Fabricante: 'Active Style',
    Preço: 99.50,
    Desconto: '5.00%',
    'Preço c/ Desconto': 94.52,
    EmEstoque: true,
  },
  {
    id: '200012',
    Selecionar: false,
    Código: 'ELET01',
    Descrição: 'Fone de Ouvido Bluetooth JBL Tune 510BT',
    Fabricante: 'JBL',
    Preço: 299.00,
    Desconto: '12.00%',
    'Preço c/ Desconto': 263.12,
    EmEstoque: true,
  },
  {
    id: '200013',
    Selecionar: false,
    Código: 'ELET02',
    Descrição: 'Smartwatch Samsung Galaxy Watch 6',
    Fabricante: 'Samsung',
    Preço: 1800.00,
    Desconto: '8.00%',
    'Preço c/ Desconto': 1656.00,
    EmEstoque: true,
  },
  {
    id: '200014',
    Selecionar: false,
    Código: 'CASA01',
    Descrição: 'Air Fryer Mondial Family AFN-40-BI 4L',
    Fabricante: 'Mondial',
    Preço: 450.00,
    Desconto: '15.00%',
    'Preço c/ Desconto': 382.50,
    EmEstoque: true,
  },
  {
    id: '200015',
    Selecionar: false,
    Código: 'CASA02',
    Descrição: 'Liquidificador Britânia Diamante 800',
    Fabricante: 'Britânia',
    Preço: 150.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 135.00,
    EmEstoque: true,
  },
  {
    id: '200016',
    Selecionar: false,
    Código: 'BELEZA01',
    Descrição: 'Creme Hidratante Facial Nivea Q10 Plus',
    Fabricante: 'Nivea',
    Preço: 49.90,
    Desconto: '5.00%',
    'Preço c/ Desconto': 47.40,
    EmEstoque: true,
  },
  {
    id: '200017',
    Selecionar: false,
    Código: 'BELEZA02',
    Descrição: 'Shampoo Elseve Reparação Total 5 400ml',
    Fabricante: 'L\'Oréal',
    Preço: 25.00,
    Desconto: '0.00%',
    'Preço c/ Desconto': 25.00,
    EmEstoque: true,
  },
  {
    id: '200018',
    Selecionar: false,
    Código: 'LIVRO01',
    Descrição: 'Livro: Hábitos Atômicos (Capa Comum)',
    Fabricante: 'Alta Books',
    Preço: 69.90,
    Desconto: '20.00%',
    'Preço c/ Desconto': 55.92,
    EmEstoque: true,
  },
  {
    id: '200019',
    Selecionar: false,
    Código: 'GAME01',
    Descrição: 'Controle DualSense PS5 Sem Fio',
    Fabricante: 'Sony',
    Preço: 399.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 359.10,
    EmEstoque: true,
  },
  {
    id: '200020',
    Selecionar: false,
    Código: 'ELET03',
    Descrição: 'Notebook Gamer Acer Nitro 5 i5 RTX 3050',
    Fabricante: 'Acer',
    Preço: 5500.00,
    Desconto: '7.00%',
    'Preço c/ Desconto': 5115.00,
    EmEstoque: true,
  },
  {
    id: '200021',
    Selecionar: false,
    Código: 'CASA03',
    Descrição: 'Aspirador de Pó Robô Xiaomi Robot Vacuum',
    Fabricante: 'Xiaomi',
    Preço: 1200.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 1080.00,
    EmEstoque: true,
  },
  {
    id: '200022',
    Selecionar: false,
    Código: 'MODA03',
    Descrição: 'Tênis Esportivo Nike Revolution 6',
    Fabricante: 'Nike',
    Preço: 299.90,
    Desconto: '0.00%',
    'Preço c/ Desconto': 299.90,
    EmEstoque: true,
  },
  {
    id: '200023',
    Selecionar: false,
    Código: 'MODA04',
    Descrição: 'Jaqueta Corta-Vento Masculina M',
    Fabricante: 'Puma',
    Preço: 180.00,
    Desconto: '15.00%',
    'Preço c/ Desconto': 153.00,
    EmEstoque: false,
  },
  {
    id: '200024',
    Selecionar: false,
    Código: 'MED011',
    Descrição: 'LISINOPRIL 10MG 30CPR (Hipertensão)',
    Fabricante: 'Novartis',
    Preço: 42.50,
    Desconto: '18.00%',
    'Preço c/ Desconto': 34.85,
    EmEstoque: true,
  },
  {
    id: '200025',
    Selecionar: false,
    Código: 'MED012',
    Descrição: 'PARACETAMOL 750MG 20CPR (Genérico)',
    Fabricante: 'Medley',
    Preço: 9.80,
    Desconto: '0.00%',
    'Preço c/ Desconto': 9.80,
    EmEstoque: true,
  },
  {
    id: '200026',
    Selecionar: false,
    Código: 'ELET04',
    Descrição: 'Smart TV LED Samsung 50 polegadas',
    Fabricante: 'Samsung',
    Preço: 2500.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 2250.00,
    EmEstoque: true,
  },
  {
    id: '200027',
    Selecionar: false,
    Código: 'CASA04',
    Descrição: 'Jogo de Panelas Tramontina Antiaderente 5pçs',
    Fabricante: 'Tramontina',
    Preço: 350.00,
    Desconto: '15.00%',
    'Preço c/ Desconto': 297.50,
    EmEstoque: true,
  },
  {
    id: '200028',
    Selecionar: false,
    Código: 'BELEZA03',
    Descrição: 'Protetor Solar Facial La Roche-Posay Anthelios 50+',
    Fabricante: 'La Roche-Posay',
    Preço: 89.90,
    Desconto: '0.00%',
    'Preço c/ Desconto': 89.90,
    EmEstoque: true,
  },
  {
    id: '200029',
    Selecionar: false,
    Código: 'ESPORTE01',
    Descrição: 'Bola de Futebol Adidas Champions League',
    Fabricante: 'Adidas',
    Preço: 120.00,
    Desconto: '5.00%',
    'Preço c/ Desconto': 114.00,
    EmEstoque: true,
  },
  {
    id: '200030',
    Selecionar: false,
    Código: 'PET01',
    Descrição: 'Ração Seca Royal Canin Cães Adultos 15kg',
    Fabricante: 'Royal Canin',
    Preço: 220.00,
    Desconto: '0.00%',
    'Preço c/ Desconto': 220.00,
    EmEstoque: true,
  },
  {
    id: '200031',
    Selecionar: false,
    Código: 'LIVRO02',
    Descrição: 'Livro: O Pequeno Príncipe (Edição de Luxo)',
    Fabricante: 'HarperCollins',
    Preço: 45.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 40.50,
    EmEstoque: true,
  },
  {
    id: '200032',
    Selecionar: false,
    Código: 'FERR01',
    Descrição: 'Furadeira de Impacto Bosch GSB 13 RE',
    Fabricante: 'Bosch',
    Preço: 320.00,
    Desconto: '8.00%',
    'Preço c/ Desconto': 294.40,
    EmEstoque: true,
  },
  {
    id: '200033',
    Selecionar: false,
    Código: 'AUTO01',
    Descrição: 'Pneu Aro 15 Michelin Energy XM2+',
    Fabricante: 'Michelin',
    Preço: 480.00,
    Desconto: '0.00%',
    'Preço c/ Desconto': 480.00,
    EmEstoque: false,
  },
  {
    id: '200034',
    Selecionar: false,
    Código: 'MED013',
    Descrição: 'FLUOXETINA 20MG 30CPR (Antidepressivo)',
    Fabricante: 'Aché',
    Preço: 55.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 49.50,
    EmEstoque: true,
  },
  {
    id: '200035',
    Selecionar: false,
    Código: 'MED014',
    Descrição: 'OMEPRAZOL 20MG 28CPR (Inibidor de Bomba)',
    Fabricante: 'Germed Pharma',
    Preço: 28.00,
    Desconto: '12.00%',
    'Preço c/ Desconto': 24.64,
    EmEstoque: true,
  },
  {
    id: '200036',
    Selecionar: false,
    Código: 'ELET05',
    Descrição: 'Câmera de Segurança Intelbras VIP 1120 B G2',
    Fabricante: 'Intelbras',
    Preço: 280.00,
    Desconto: '5.00%',
    'Preço c/ Desconto': 266.00,
    EmEstoque: true,
  },
  {
    id: '200037',
    Selecionar: false,
    Código: 'CASA05',
    Descrição: 'Máquina de Lavar Brastemp BWL11AB 11kg',
    Fabricante: 'Brastemp',
    Preço: 1800.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 1620.00,
    EmEstoque: true,
  },
  {
    id: '200038',
    Selecionar: false,
    Código: 'BELEZA04',
    Descrição: 'Perfume Kaiak Masculino Natura 100ml',
    Fabricante: 'Natura',
    Preço: 150.00,
    Desconto: '20.00%',
    'Preço c/ Desconto': 120.00,
    EmEstoque: true,
  },
  {
    id: '200039',
    Selecionar: false,
    Código: 'MODA05',
    Descrição: 'Vestido Florido Feminino G',
    Fabricante: 'Zara',
    Preço: 199.00,
    Desconto: '0.00%',
    'Preço c/ Desconto': 199.00,
    EmEstoque: true,
  },
  {
    id: '200040',
    Selecionar: false,
    Código: 'MED015',
    Descrição: 'AMOXICILINA 500MG 21CPR (Antibiótico)',
    Fabricante: 'EMS Pharma',
    Preço: 65.00,
    Desconto: '15.00%',
    'Preço c/ Desconto': 55.25,
    EmEstoque: true,
  },
  {
    id: '200041',
    Selecionar: false,
    Código: 'MED016',
    Descrição: 'IBUPROFENO 600MG 10CPR (Anti-inflamatório)',
    Fabricante: 'Eurofarma',
    Preço: 25.00,
    Desconto: '5.00%',
    'Preço c/ Desconto': 23.75,
    EmEstoque: true,
  },
  {
    id: '200042',
    Selecionar: false,
    Código: 'ELET06',
    Descrição: 'Echo Dot 5ª Geração com Alexa',
    Fabricante: 'Amazon',
    Preço: 350.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 315.00,
    EmEstoque: true,
  },
  {
    id: '200043',
    Selecionar: false,
    Código: 'CASA06',
    Descrição: 'Cafeteira Elétrica 30 Xícaras Philco',
    Fabricante: 'Philco',
    Preço: 130.00,
    Desconto: '10.00%',
    'Preço c/ Desconto': 117.00,
    EmEstoque: true,
  },
  {
    id: '200044',
    Selecionar: false,
    Código: 'BELEZA05',
    Descrição: 'Kit Maquiagem Completo Vult',
    Fabricante: 'Vult',
    Preço: 180.00,
    Desconto: '8.00%',
    'Preço c/ Desconto': 165.60,
    EmEstoque:false,
  }
]